name: CI

on:
  # Trigger the workflow on push or pull request, but only for non-main branches
  push:
    branches-ignore:
      - main
  # This workflow can be reused by other workflows
  workflow_call:

jobs:
  # Run tests
  run_tests:
    name: Run Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./modules
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '21'

      - name: Run All Tests
        run: mvn test

  # Check guidelines
  check_guidelines:
    name: Check Guidelines
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./modules
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '21'

      - name: Check License Headers
        run: mvn license:check

  # Check code style
  check_code_style:
    name: Check Code Style
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./modules
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '21'

      - name: Check Code Style
        run: mvn spotless:check
